---
- name: '[airline] install custom vim-airline themes per user'
  copy:
    src: "airline-custom-themes/solarized_custom.vim"
    dest: "~/.vim/\
          {{ 'bundle' if 'vundle' in vim_plugin_manager else 'plugged' if 'plug' in vim_plugin_manager }}\
          /vim-airline-themes/autoload/airline/themes/"
    owner: "{{ vim_airline_user }}"
    group: "{{ vim_airline_user if ansible_os_family != 'Darwin' else 'wheel' if vim_airline_user == 'root' else 'staff' }}"
  loop: "{{ vim_users }}"
  loop_control:
    loop_var: vim_airline_user
  become: yes
  become_user: "{{ vim_airline_user }}"
  when: "'user' in vim_env"
  tags: vim

- name: '[airline] install custom vim-airline themes system-wide'
  copy:
    src: "airline-custom-themes/solarized_custom.vim"
    dest: "/etc/vim/\
          {{ 'bundle' if 'vundle' in vim_plugin_manager else 'plugged' if 'plug' in vim_plugin_manager }}\
          /vim-airline-themes/autoload/airline/themes/"
    owner: root
    group: root
  become: yes
  when: "'system' in vim_env"
  tags: vim
...
