---
- name: '[non-Darwin] Make sure vim-tiny is uninstalled'
  package: name=vim-tiny state=absent purge=true
  register: vim_install_result
  until: vim_install_result is succeeded
  become: yes
  tags: vim

- name: '[non-Darwin] Make sure vim-nox is installed'
  package: name=vim-nox state=present
  register: vim_remove_result
  until: vim_remove_result is succeeded
  become: yes
  tags: vim

# Analog of 'update-alternatives --set editor /usr/bin/vim.nox'
- name: '[non-Darwin] Setting vim default editor for visudo'
  alternatives:
    name: editor
    path: /usr/bin/vim.nox
  become: yes
  tags: vim
...
