---
- name: '[nvim] Install neovim on Darwin'
  homebrew:
    name: neovim
  become: no
  register: vim_neovim_install_result
  until: vim_neovim_install_result is succeeded
  when: "'Darwin' in ansible_os_family"
  tags: vim

- name: '[nvim] Install neovim on non-Darwin systems'
  package:
    name: neovim
  become: yes
  register: vim_neovim_install_result
  until: vim_neovim_install_result is succeeded
  when: "not 'Darwin' in ansible_os_family"
  tags: vim

- name: '[nvim] Create neovim configuration by symlinking the existing vim config'
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
  - { src: '~/.vim', dest: '~/.config/nvim' }
  - { src: '~/.vimrc', dest: '~/.vim/init.vim' }
  #- { src: "{{ vim_root_config }}", dest: '~/.vim/init.vim' }
  when: "'user' in vim_env"
  tags: vim
...
